FROM node:16-alpine

#when you are mounting volumes it is better to use a user so you can avoid permission issues when running npm start
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]