version: '3'
services:
  nginx:
    image: "docker2dl5g/multi-nginx-10-14"
    hostname: nginx
    ports:
      - "80:80"
  #no postgres or redis containers as those are managed services
  api:
    image: "docker2dl5g/multi-server-10-14"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: "docker2dl5g/multi-client-10-14"
    hostname: client
  worker:
    image: "docker2dl5g/multi-worker-10-14"
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT